dist: xenial
services:
  - docker
language: node_js
node_js: 6.17
cache: npm
env:
  - DOCKER_COMPOSE_VERSION=1.24.0
before_install: './before_install.sh ${DOCKER_COMPOSE_VERSION}'
script: './script.sh ens4'
