dist: xenial
services:
  - docker
language: node_js
node_js: 6.17
cache:
  npm:
  directories:
    - /usr/local/bin
env:
  - DOCKER_COMPOSE_VERSION=1.24.0
before_install: './before_install.sh ${DOCKER_COMPOSE_VERSION}'
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
script: './script.sh ens4 amissine'
